[project]
name = 'poll-counter'
description = "A polling system smart contract"
license = "MIT"
authors = ["Samuel Okechukwu"]
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 2.1
epoch = 2.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false

[network]
name = "testnet"