[project]
name = 'poll-counter'
description = 'A polling system smart contract'
authors = ['Samuel Okechukwu']
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 2
epoch = 2.5

[contracts.voter-reward]
path = 'contracts/voter-reward.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
